### ISSUE TITLE
GitHub won't let me fork an empty repo.

### ISSUE THREAD

**Issue by tangmi** [StudentRND/s5#1]

**Comment by tylermenezes** [comment]
@tangmi can you confirm this issue was resolved in 0272eb8136?

**Comment by tangmi** [comment]
I have commit (null) in production and the problem persists. Is it possible to create a hotfix for version 0.0.0?

**Comment by tjhorner** [comment]
Forked repo. Can't reproduce. Should be fixed in 0272eb8.
